### ISSUE TITLE
Add ability to automatically release a major/minor/patch beta

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-version#114]
## What
Currently the beta feature only works to create a beta on the current version, which is not always what we want.

Let's add the ability for this github action to add increment the major/minor/patch at the same time as adding the beta label.

## Additional information

@chee suggested an implementation for this which is:

Allow the `release:beta` label to be applied to a pull-request at the same time as a `release:major`/`release:minor`/`release:patch` label.

- If `release:major` and `release:beta` are applied: do an `npm version premajor`
- If `release:minor` and `release:beta` are applied: do an `npm version preminor`
- If `release:patch` and `release:beta` are applied: do an `npm version prepatch`
- If only `release:beta` is applied: do an `npm version prerelease`

**Comment by notlee** [comment]
I've started working on this
